name: Galaxy Tool Linting and Tests for push and PR
on:
  pull_request:
  push:
    branches:
      - main
      - master
env:
  GALAXY_FORK: galaxyproject
  GALAXY_BRANCH: release_22.05
  MAX_CHUNKS: 4
  MAX_FILE_SIZE: 1M
concurrency:
  # Group runs by PR, but keep runs on the default branch separate
  # because we do not want to cancel ToolShed uploads
  group: pr-${{ (github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main') && github.run_number || github.ref }}
  cancel-in-progress: true
jobs:
  determine-success:
    name: Check workflow success
    runs-on: ubuntu-latest
    steps:
      -  run: 'echo "No tool tests required"'
